INSERT INTO "user" VALUES (DEFAULT, 'Den');
INSERT INTO "user" VALUES (DEFAULT, 'Fil');
INSERT INTO "user" VALUES (DEFAULT, 'Nicol');
INSERT INTO "user" VALUES (DEFAULT, 'Grisha');
INSERT INTO "user" VALUES (DEFAULT, 'Alex');
INSERT INTO "user" VALUES (DEFAULT, 'Ben');

