INSERT INTO "car" VALUES (DEFAULT,1, 'Opel');
INSERT INTO "car" VALUES (DEFAULT,2, 'VolksWagen');
INSERT INTO "car" VALUES (DEFAULT,3, 'BMW');
INSERT INTO "car" VALUES (DEFAULT,3, 'Fiat');
INSERT INTO "car" VALUES (DEFAULT,4, 'Ford');
INSERT INTO "car" VALUES (DEFAULT,5, 'Doodge');

